# General Jekyll Config
highlighter: rouge
url: http://imfong.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
paginate: 20
paginate_path: "page:num"
permalink: /post/:title
markdown: redcarpet  
gems: [jekyll-paginate]
