# Site settings
title: maxfong's Homepage
email: devmaxfong@qq.com
description: blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maxfong.xyz" # the base hostname & protocol for your site
twitter_username: maxfongDev
github_username:  maxfong

# Build settings
markdown: kramdown
