# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://imfong.com
date_format: "ordinal"
title: maxfong的博客
subtitle: "多学，多思"
description: "maxfong的个人博客"
keywords: maxfong, max, fal, ios
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: maxfong
organization: 同程旅游
organization_url: https://ly.com
github_username: maxfong
location: SuZhou, China
email: devmaxfong@qq.com
gravatar: 35f2dd12f762a45a2e85d4096a9b11f2

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  # -
  #   href: /
  #   label: 首页

  -
    href: /categories/
    label: 分类

  # -
  #   href: /wiki/
  #   label: 维基

  # -
  #   href: /links/
  #   label: 链接

  # -
  #   href: /about/
  #   label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
paginate_path: "page:num"
permalink: /post/:title
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
# collections:
#     wiki:
#         output: true
#         permalink: /wiki/:path/

repository: maxfong/maxfong.github.com

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: netease_gentie
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
netease_gentie_key: ef6f8c2b68724652a938e184ea921522
# 在使用网易云跟帖时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-97303967-1
